#pragma once

/*************************************************************************************/
//
//			                    Copyright 2022 Max J. Martin
//
//			                    This file is part of Oliver.
//
//      Boost Software License - Version 1.0 - August 17th, 2003
//
//      Permission is hereby granted, free of charge, to any person or organization
//      obtaining a copy of the software and accompanying documentation covered by
//      this license(the "Software") to use, reproduce, display, distribute,
//      execute, and transmit the Software, and to prepare derivative works of the
//      Software, and to permit third - parties to whom the Software is furnished to
//      do so, all subject to the following :
//
//      The copyright notices in the Software and this entire statement, including
//      the above license grant, this restriction and the following disclaimer,
//      must be included in all copies of the Software, in whole or in part, and
//      all derivative works of the Software, unless such copies or derivative
//      works are solely in the form of machine - executable object code generated by
//      a source language processor.
//
//      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//      FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON - INFRINGEMENT.IN NO EVENT
//      SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//      FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//      ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//      DEALINGS IN THE SOFTWARE.
//			
/*************************************************************************************/

#include <map>
#include "base_type_definitions.h"

namespace Olly {

    /********************************************************************************************/
    //
    //                                 Interpreter Operator ENUM
    // 
    //          This file is required by the 'var' class.  But at this time is not used
    //          in any other data types.  This will be updated once the 'op_code' data 
    //          type is reimplemented.
    //
    /********************************************************************************************/

    const enum class OP_CODE {
        nothing_op = 0,

        /************************** Compile Time Operators ***************************/

        PREFIX_OPERATORS_START,

        idnt_op, neg_op,

        PREFIX_OPERATORS_STOP,

        INFIX_OPERATORS_START,

        AND_op, OR_op, XOR_op,
        ADD_op, SUB_op, MUL_op, DIV_op, MOD_op, FDIV_op, REM_op, POW_op,
        EQ_op, NE_op, LT_op, LE_op, GT_op, GE_op,
        L_AND_op, L_OR_op, L_XOR_op,
        LEAD_op, JOIN_op, DROP_op,

        BIND_op, APPLY_op,

        INFIX_OPERATORS_STOP,

        /**************************** Runtime Operators *****************************/


        deque_op, emit_op, endl_op, enter_op,
        assign_op, let_op,
        is_def_op, size_op, type_op,
        l_eq_op, L_CON_op, l_imp_op,
        if_op, elif_op, else_op,
        lambda_op, def_op, end_scope_op,
        FUNDAMENTAL_OPERATORS,

        lead_op, join_op, drop_op,
        deque_lead_op, deque_join_op, deque_drop_op,
        SEQUENTIAL_OPERATORS,

        add_op, sub_op, mul_op, div_op, mod_op, fdiv_op, rem_op, pow_op,
        eq_op, ne_op, lt_op, le_op, gt_op, ge_op,
        l_and_op, l_or_op, l_xor_op,
        BINARY_OPERATORS,

        bool_alpha_op, bool_numeric_op,
        IO_OPERATORS,



        apply_op, has_op, get_op, set_op, del_op, bind_op,
        FUNCTIONAL_OPERATORS,

        map_op, clear_op,

        result_op,

        END_OPERATORS
    };

    /********************************************************************************************/
    //
    //                                 Interpreter Operator Map
    //
    /********************************************************************************************/

    static const std::map<Text, OP_CODE> OPERATORS = {

        // Fundamental Operators
        { "none",            OP_CODE::nothing_op },    { "nothing",         OP_CODE::nothing_op },
        { "idnt",               OP_CODE::idnt_op },    { "deque",             OP_CODE::deque_op },
        { "<<",                 OP_CODE::emit_op },    { ">>",                OP_CODE::enter_op },
        { "assign",           OP_CODE::assign_op },    { "let",                 OP_CODE::let_op },
        { "if",                   OP_CODE::if_op },    { "is",               OP_CODE::is_def_op },
        { "elif",               OP_CODE::elif_op },    { "else",               OP_CODE::else_op },
        { "lambda",           OP_CODE::lambda_op },    { "def",                 OP_CODE::def_op },
        { "neg",                 OP_CODE::neg_op },    { "endl",               OP_CODE::endl_op },
        // TOFO: add a 'cat' operator to get the category classification of an object.

        // Fundamental Sequential Operators
        { "lead",               OP_CODE::lead_op },    { "<--",                OP_CODE::LEAD_op },
        { "join",               OP_CODE::join_op },    { "<->",                OP_CODE::JOIN_op },
        { "drop",               OP_CODE::drop_op },    { "-->",                OP_CODE::DROP_op },
        { "LEAD",         OP_CODE::deque_lead_op },
        { "JOIN",         OP_CODE::deque_join_op },
        { "DROP",         OP_CODE::deque_drop_op },

        // Binary Postfix Mathmatical Operators
        { "_+",                 OP_CODE::add_op },    { "_-",                  OP_CODE::sub_op },
        { "_*",                 OP_CODE::mul_op },    { "_/",                  OP_CODE::div_op },
        { "_%",                 OP_CODE::mod_op },    { "_//",                OP_CODE::fdiv_op },
        { "_%%",                OP_CODE::rem_op },    { "_**",                 OP_CODE::pow_op },

        // Binary Infix Mathmatical Operators
        { "+",                   OP_CODE::ADD_op },    { "-",                  OP_CODE::SUB_op },
        { "*",                   OP_CODE::MUL_op },    { "/",                  OP_CODE::DIV_op },
        { "%",                   OP_CODE::MOD_op },    { "//",                OP_CODE::FDIV_op },
        { "%%",                  OP_CODE::REM_op },    { "**",                 OP_CODE::POW_op },

        // Binary Postfix Relational Operators
        { "_=",                   OP_CODE::eq_op },    { "_<=",                 OP_CODE::le_op },
        { "_-=",                  OP_CODE::ne_op },    { "_>",                  OP_CODE::gt_op },
        { "_<",                   OP_CODE::lt_op },    { "_>=",                 OP_CODE::ge_op },

        // Binary Infix Relational Operators
        { "=",                    OP_CODE::EQ_op },    { "-=",                  OP_CODE::NE_op },
        { "<=",                   OP_CODE::LE_op },    { ">=",                  OP_CODE::GE_op },
        { "<",                    OP_CODE::LT_op },    { ">",                   OP_CODE::GT_op },

        // Binary Infix and Postfix Logical Operators
        { "&",                 OP_CODE::L_AND_op },    { "_&",               OP_CODE::l_and_op },
        { "|",                  OP_CODE::L_OR_op },    { "_|",                OP_CODE::l_or_op },
        { "^",                 OP_CODE::L_XOR_op },    { "_^",               OP_CODE::l_xor_op },
        { "?",                 OP_CODE::L_CON_op },    { "_?",               OP_CODE::l_imp_op },

        // Binary Infix and Postfix Logical Operators
        { "bool_alpha",        OP_CODE::bool_alpha_op },    { "bool_numeric",    OP_CODE::bool_numeric_op },



        // TODO: sort below operations

        { "size",               OP_CODE::size_op },    { "size",               OP_CODE::size_op },


        // print, str, repr, ...

        //  Operators to sort.


        { "get",                 OP_CODE::get_op },    { "has",                 OP_CODE::has_op },
        { "set",                 OP_CODE::set_op },    { "del",                 OP_CODE::del_op },

        /****************************************************************************/





        //{ "loop",         OP_CODE::loop_op },
        //{ "imply",       OP_CODE::imply_op },   { "else",        OP_CODE::else_op },


        //{ "cond",         OP_CODE::cond_op },
        //{ "const?",   OP_CODE::is_const_op },
        //{ "var?",       OP_CODE::is_var_op },



    };

}
